/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author alu20925322z
 */
public class ScoreBoard extends javax.swing.JPanel {
    
    private int score = 5;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        ScoreBoardLabel.setText("Size: " + score);
    }
    
    public int getScore(){
        return score;
    }
    
    public void setScore(int score){
        this.score = score;
        ScoreBoardLabel.setText("Size: " + score);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScoreBoardLabel = new javax.swing.JLabel();

        ScoreBoardLabel.setText("jLabel1");
        add(ScoreBoardLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScoreBoardLabel;
    // End of variables declaration//GEN-END:variables
}
